# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2019-03-18 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TestModel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='administrator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_name', models.CharField(max_length=20)),
                ('adm_password', models.CharField(max_length=20)),
                ('adm_email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=20)),
                ('emp_sex', models.CharField(max_length=10)),
                ('emp_age', models.IntegerField()),
                ('emp_category', models.CharField(max_length=50)),
                ('pro_id', models.IntegerField()),
                ('pro_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pro_name', models.CharField(max_length=50)),
                ('pro_start', models.DateField()),
                ('pro_end', models.DateField()),
                ('pro_cycle', models.CharField(max_length=20)),
                ('pro_category', models.CharField(max_length=50)),
            ],
        ),
    ]
